version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000/api}
    volumes:
      - ./.env.local:/app/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000/api}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 